name: Build and publish Docker Image

on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Application to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jetalone/coorseo-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          dockerfile: Dockerfile
          snapshot: true
          tag_names: true
          